project/apps/core/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, Contact

app_name='core'

urlpatterns = [
    path ('', HomeView.as_view(), name='home'),
    path('contato/', Contact, name='contact'),
]

project/apps/courses/urls.py
from django.urls import path
from .views import index, details

app_name='courses'

urlpatterns = [
    path ('', index, name='index'),
    path ('<slug>', details, name='details' )
]

project/apps/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls',namespace='core')),
    path('cursos/', include('apps.courses.urls',namespace='courses')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/apps/core/models.py
from django.db import models

# Create your models here.

project/apps/core/forms.py
from django import forms
from django.contrib.auth import password_validation
from material import Layout, Row

from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, UserChangeForm

from apps.accounts.models import User


class UpdateProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def clean_password(self):
        return self.clean_password

project/apps/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

from .forms import UpdateProfileForm


# Create your views here.

class HomeView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    template_name = 'home.html'
    form_class = UpdateProfileForm
    success_url = reverse_lazy('core:home')
    success_message = "Suas informações foram alteradas com sucesso."

    def get_object(self, queryset=None):
        return self.request.user

def Contact(request):    
    return render(request, 'contact.html')

project/apps/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Plataforma JARS - Empreender para transformar" />
    <title> JARS | Plataforma</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

</head>

<body>
    {% block body %}

    {% endblock %}
</body>

</html>

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'materialize//css/materialize.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/header_footer.js' %}"></script>
    <script type="text/javascript" src="{% static 'materialize/js/materialize.js' %}"></script>
    <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
{% endblock %}

project/apps/core/templates/contact.html
{% extends "header_footer.html" %}

{% block content %}
    <div class="container">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@jars.org.br">contato@jars.org.br</a></li>
                <li>Facebook: <a href="https://facebook.com/jars">Junior Achievement RS</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

project/apps/core/templates/header_footer.html
{% include 'base.html' %}

{% block body %}
        <nav class="light-blue lighten-1 valign-wrapper" role="navigation">
            <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Jars</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'core:home' %}">Início</a></li>
                    <li><a href="{% url 'courses:index' %}">Cursos</a></li>
                    <li><a href="{% url 'core:contact' %}">Contato</a></li>
                </ul>
                <ul id="nav-mobile" class="sidenav">
                    <li><a href="{% url 'core:home' %}">Início</a></li>
                    <li><a href="{% url 'courses:index' %}">Cursos</a></li>
                    <li><a href="{% url 'core:contact' %}">Contato</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
        </nav>
        <div id="main-content">
            {% block content %}{% endblock %}
        </div>
        <footer>
                <div class="container center">
                    Associação Junior Achievement do Rio Grande do Sul - Todos os direitos reservados
                </div>
        </footer>
{% endblock %}

project/apps/core/templates/home.html
{% extends 'header_footer.html' %}

{% block content %}

{% load material_form %}

<div class="container">
        <div id="test1" class="col s12">
            <div class="card card-profile" style="padding:3%;">
                <nav class="nav-extended grey lighten-1">
                    <div class="nav-content" role='navigation'>
                        <ul class="tabs tabs-transparent">
                            <li class="tab"><a class="active" href="#test1">My account</a></li>
                            <li class="tab"><a href="#test2">My Courses</a></li>
                            <li class="tab"><a href="#test3">Test 3</a></li>
                        </ul>
                    </div>
                </nav>
                <div class="row">
                    <div class="card-content">
                        <div class="col s12 m3">
                            <div class="center">
                                <span class="card-title">{{user.first_name}} {{user.last_name}}</span>
                                <img class="profile-image" src="{{ request.user.profile_picture.url }}">
                                </a><br>
                                <i class="material-icons">edit</i>alterar foto
        
                                </a>
                            </div>
                        </div>
                        <div class="col s12 m9">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div>
                                    <button type="submit" name="_submit" class="btn waves-effect waves-light">Salvar</button>
                                    <a href="" class="btn btn-flat white waves-effect">Cancelar</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
</div>

{% endblock %}